// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_message.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.proto;

public final class UserMessageProto {
  private UserMessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      UserMessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_proto_UserMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_proto_UserMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user_message.proto\022\026com.example.demo.p" +
      "roto\"\221\001\n\013UserMessage\022\n\n\002id\030\001 \001(\t\022\020\n\010user" +
      "name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\017\n\007message\030\004 \001" +
      "(\t\022\021\n\ttimestamp\030\005 \001(\003\0221\n\004type\030\006 \001(\0162#.co" +
      "m.example.demo.proto.MessageType*/\n\013Mess" +
      "ageType\022\010\n\004INFO\020\000\022\013\n\007WARNING\020\001\022\t\n\005ERROR\020" +
      "\002B,\n\026com.example.demo.protoB\020UserMessage" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_proto_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_proto_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_proto_UserMessage_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "Message", "Timestamp", "Type", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
