plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-jooq'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'mysql:mysql-connector-java:8.0.33'
	implementation 'com.zaxxer:HikariCP:4.0.3'

	implementation 'net.logstash.logback:logstash-logback-encoder:8.1'
	implementation 'ch.qos.logback:logback-classic:1.5.18'

	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	// Micrometer for Datadog
	runtimeOnly 'io.micrometer:micrometer-registry-datadog'
	// Datadog Tracing
	implementation 'com.datadoghq:dd-trace-api:1.48.0' // Use the latest version
	// Spring Boot Actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.testcontainers:testcontainers:1.19.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
