plugins {
    id 'java'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.4.5' apply false
}

group = 'com.example'
version = '1.0.0'

allprojects {
    repositories {
        mavenCentral()
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:3.4.5"
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.example'
            artifactId = 'custom-spring-boot-starter-parent'
            version = '1.0.0'
            pom.packaging = 'pom'
        }
    }
    repositories {
        mavenLocal()
    }
}
