services:
  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092"
    environment:
      # Auto create topics on first use
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8880:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka

  mysql:
    image: mysql:8.4.5
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    ports:
      - "8126:8126"
      - "8125:8125"
    restart: always
    pid: host
    environment:
      DD_API_KEY: <YOUR_API_KEY>
      DD_SITE: datadoghq.com
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_APM_ENABLED: true
      DD_AGENT_HOST: dd-agent
      DD_LOGS_ENABLED: true
      DD_CONTAINER_EXCLUDE_LOGS: "name:dd-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log/demo:/logs:ro
      - ./datadog/app/conf.yaml:/conf.d/logs.d/conf.yaml:ro
      - ./datadog/pgbouncer.d/conf.yaml:/conf.d/pgbouncer.d/conf.yaml:ro

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.0-p1
    container_name: pgbouncer
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro

volumes:
  mysql-data:
  redis_data:
  pg-data:
