spring.application.name=demo

spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/rambo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&nullDatabaseMeansCurrent=true&createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
