plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management'
	id 'com.diffplug.spotless' version '6.25.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

spotless {
	java {
		googleJavaFormat('1.22.0').aosp() // AOSP style uses 4-space indentation. Latest version as of June 2025
	}
}


repositories {
	mavenCentral()
	mavenLocal() // Required to find the parent in the local repository
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-jooq'
	runtimeOnly 'mysql:mysql-connector-java:8.0.33'

	implementation 'org.springframework.kafka:spring-kafka'

	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	// Spring Boot Actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.testcontainers:testcontainers'
	testImplementation 'org.testcontainers:mysql'
	testImplementation 'org.testcontainers:junit-jupiter'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

bootRun {
	jvmArgs = ['-Xmx100m', '-XX:MaxDirectMemorySize=32m', '-XX:+HeapDumpOnOutOfMemoryError', '-XX:HeapDumpPath=build/dump.hprof', '-XX:+PrintFlagsFinal']
}
